version: "3.8"
services:
  mongo:
    image: mongo:7.0
    restart: unless-stopped
    ports: ["27017:27017"]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=1234
    volumes:
      - ./data:/data/db
      - .:/work
